import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// A barra lateral é gerada a partir da estrutura de pastas em docs/.
// A ordem vem de `sidebar_position` (páginas) e `position` (_category_.json).
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
